### ISSUE TITLE
TypeError: Expected 'Iterator' as the return annotation for `__iter__` of SMILESParser, but found typing.Any

### ISSUE THREAD

**Issue by ChenXun1** [nicolas-hbt/semantic-lossfunc#1]

**Comment by jwm1d** [comment]
Hello! Have you fixed this problem? I encountered a same one during the proccess of running point-transformer-V2 network for point cloud semantic segmentation.

**Comment by jwm1d** [comment]
You close it since you can't solve it? Stupid thing!~
