### ISSUE TITLE
Missing was_last_batch（）function

### ISSUE THREAD

**Issue by ChenXun1** [nicolas-hbt/semantic-lossfunc#2]
AttributeError: 'Dataset' object has no attribute 'was_last_batch'
@nicolas-hbt Hello, the was_last_batch（） function is missing. Looking forward to your reply.

**Comment by nicolas-hbt** [comment]
Hi @ChenXun1
The code has recently been updated. The was_last_batch() function was missing indeed. Should be working fine now.
